### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [kevinherron/opc-ua-stack#25]
Hi
The following lines have cryptographic API misuses. <br> File name => stack-core/src/main/java/com/digitalpetri/opcua/stack/core/channel/ChunkDecoder.java: Line number => 330: API name => SecretKeySpec:<BR> File name => stack-core/src/main/java/com/digitalpetri/opcua/stack/core/channel/ChunkDecoder.java: Line number => 250: API name => Signature:<BR> File name => stack-core/src/main/java/com/digitalpetri/opcua/stack/core/util/SignatureUtil.java: Line number => 80: API name => SecretKeySpec:<BR> File name => stack-core/src/main/java/com/digitalpetri/opcua/stack/core/channel/ChunkDecoder.java: Line number => 172: API name => Cipher:<BR> File name => stack-core/src/main/java/com/digitalpetri/opcua/stack/core/channel/ChunkEncoder.java: Line number => 168: API name => Cipher:<BR> File name => stack-core/src/main/java/com/digitalpetri/opcua/stack/core/channel/ChunkDecoder.java: Line number => 223: API name => Cipher:Operation on object of type javax.crypto.Cipher object not completed. Expected call to <javax.crypto.Cipher: int doFinal(byte[],int,int,byte[])>, <javax.crypto.Cipher: byte[] doFinal(byte[])>, <javax.crypto.Cipher: int doFinal(java.nio.ByteBuffer,java.nio.ByteBuffer)>, update, <javax.crypto.Cipher: byte[] doFinal(byte[],int,int)>, <javax.crypto.Cipher: int doFinal(byte[],int,int,byte[],int)><BR> File name => stack-core/src/main/java/com/digitalpetri/opcua/stack/core/channel/ChunkEncoder.java: Line number => 255: API name => Cipher:Operation on object of type javax.crypto.Cipher object not completed. Expected call to <javax.crypto.Cipher: int doFinal(byte[],int,int,byte[])>, <javax.crypto.Cipher: byte[] doFinal(byte[])>, <javax.crypto.Cipher: int doFinal(java.nio.ByteBuffer,java.nio.ByteBuffer)>, update, <javax.crypto.Cipher: byte[] doFinal(byte[],int,int)>, <javax.crypto.Cipher: int doFinal(byte[],int,int,byte[],int)><BR> File name => stack-core/src/main/java/com/digitalpetri/opcua/stack/core/channel/ChunkDecoder.java: Line number => 330: API name => SecretKeySpec:<BR> File name => stack-core/src/main/java/com/digitalpetri/opcua/stack/core/util/SignatureUtil.java: Line number => 56: API name => Signature:<BR> File name => stack-core/src/main/java/com/digitalpetri/opcua/stack/core/util/DigestUtil.java: Line number => 47: API name => MessageDigest:<BR> File name => stack-core/src/main/java/com/digitalpetri/opcua/stack/core/util/DigestUtil.java: Line number => 40: API name => MessageDigest:First parameter (with value "SHA1") should be any of {SHA-256, SHA-384, SHA-512}<BR> File name => stack-core/src/main/java/com/digitalpetri/opcua/stack/core/channel/ChunkDecoder.java: Line number => 333: API name => Cipher:Operation on object of type javax.crypto.Cipher object not completed. Expected call to <javax.crypto.Cipher: int doFinal(byte[],int,int,byte[])>, <javax.crypto.Cipher: byte[] doFinal(byte[])>, <javax.crypto.Cipher: int doFinal(java.nio.ByteBuffer,java.nio.ByteBuffer)>, update, <javax.crypto.Cipher: byte[] doFinal(byte[],int,int)>, <javax.crypto.Cipher: int doFinal(byte[],int,int,byte[],int)><BR> File name => stack-core/src/main/java/com/digitalpetri/opcua/stack/core/util/PShaUtil.java: Line number => 52: API name => Mac:Unexpected call to method init on object of type javax.crypto.Mac.<BR> File name => stack-core/src/main/java/com/digitalpetri/opcua/stack/core/channel/ChunkEncoder.java: Line number => 173: API name => Cipher:<BR> File name => stack-core/src/main/java/com/digitalpetri/opcua/stack/core/util/PShaUtil.java: Line number => 73: API name => SecretKeySpec:<BR> File name => stack-core/src/main/java/com/digitalpetri/opcua/stack/core/channel/ChunkDecoder.java: Line number => 259: API name => Signature:<BR> File name => stack-core/src/main/java/com/digitalpetri/opcua/stack/core/channel/ChunkDecoder.java: Line number => 169: API name => Cipher:<BR> File name => stack-core/src/main/java/com/digitalpetri/opcua/stack/core/channel/ChunkEncoder.java: Line number => 344: API name => SecretKeySpec:<BR> File name => stack-core/src/main/java/com/digitalpetri/opcua/stack/core/util/SignatureUtil.java: Line number => 49: API name => Signature:Unexpected call to method sign on object of type java.security.Signature. Expect a call to one of the following methods initSign,update<BR> File name => stack-core/src/main/java/com/digitalpetri/opcua/stack/core/channel/ChunkEncoder.java: Line number => 173: API name => Cipher:<BR> File name => stack-core/src/main/java/com/digitalpetri/opcua/stack/core/channel/ChunkEncoder.java: Line number => 344: API name => SecretKeySpec:<BR> File name => stack-core/src/main/java/com/digitalpetri/opcua/stack/core/channel/ChunkDecoder.java: Line number => 169: API name => Cipher:<BR> File name => stack-core/src/main/java/com/digitalpetri/opcua/stack/core/util/SignatureUtil.java: Line number => 80: API name => SecretKeySpec:<BR> File name => stack-core/src/main/java/com/digitalpetri/opcua/stack/core/channel/ChunkDecoder.java: Line number => 331: API name => IvParameterSpec:<BR> File name => stack-core/src/main/java/com/digitalpetri/opcua/stack/core/channel/ChunkEncoder.java: Line number => 347: API name => Cipher:Operation on object of type javax.crypto.Cipher object not completed. Expected call to update, doFinal<BR> File name => stack-core/src/main/java/com/digitalpetri/opcua/stack/core/util/PShaUtil.java: Line number => 73: API name => SecretKeySpec:<BR> File name => stack-core/src/main/java/com/digitalpetri/opcua/stack/core/channel/ChunkDecoder.java: Line number => 172: API name => Cipher:<BR> File name => stack-core/src/main/java/com/digitalpetri/opcua/stack/core/channel/ChunkEncoder.java: Line number => 168: API name => Cipher:<BR> File name => stack-core/src/main/java/com/digitalpetri/opcua/stack/core/util/DigestUtil.java: Line number => 47: API name => MessageDigest:<BR> File name => stack-core/src/main/java/com/digitalpetri/opcua/stack/core/util/CertificateGenerator.java: Line number => 102: API name => KeyStore:Second parameter should never be of type java.lang.String.<BR> File name => stack-core/src/main/java/com/digitalpetri/opcua/stack/core/channel/ChunkEncoder.java: Line number => 345: API name => IvParameterSpec:<BR> File name => stack-examples/src/main/java/com/digitalpetri/opcua/stack/examples/ClientServerExample.java: Line number => 98: API name => KeyStore:Second parameter should never be of type java.lang.String.<BR> File name => stack-examples/src/main/java/com/digitalpetri/opcua/stack/examples/ClientServerExample.java: Line number => 108: API name => KeyStore:<BR> File name => stack-examples/src/main/java/com/digitalpetri/opcua/stack/examples/ClientServerExample.java: Line number => 101: API name => KeyStore:<BR>

**Comment by kevinherron** [comment]
go away, bot. this repo is not maintained.
